### ISSUE TITLE
Seperate sections for open source owned by GC and contribution to OSS not owned by GC

### ISSUE THREAD

**Issue by LaurentGoderre** [canada-ca/open-source-logiciel-libre#14]
The requirements for GC employees contributing to GC owned projects probably should be different than those for GC employees contributing to project not owned by the GC. Should this document make that distinction?

**Comment by gcharest** [comment]
We're trying to separate the two scenarios based on the two requirements A and B.

From the latest version, do you feel that the distinction is not sufficiently clear?

**Comment by LaurentGoderre** [comment]
Maybe it's just the title then that may lead to confusion

**Comment by gcharest** [comment]
Hi @LaurentGoderre !

We have split the document to better reflect the difference as stated in the initial question.

We'll close the issue for now.

Thanks!

Guillaume
