### ISSUE TITLE
CVS are considered deprecated.

### ISSUE THREAD

**Issue by mgifford** [canada-ca/open-source-logiciel-libre#15]
I'd change this to "CVS and Subversion are considered deprecated."

**Comment by gcharest** [comment]
Hi @mgifford !

I'll look into it shortly, I think the idea was to identify that centralized VCS should be considered deprecated, but we probably should provide examples of them.

Thanks!

**Comment by ShadeWyrm** [comment]
The document no longer contains references to this. Closing. :)
