### ISSUE TITLE
Clarification on Protected Information - Tests, Testing Procedures, and Audits

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/open-source-logiciel-libre#2]
I would like clarification on what Information about testing procedures, tests, and audits is considered protected information? The document doesn't specify the type of tests and I can see there being confusion when the open source software has tests that automate the software. 

Link to Section : https://github.com/canada-ca/open-source-contribution-logiciel-libre/blob/master/en/contribution.md#protected-information 

My issue in the open first whitepaper can be closed in favor of this one: https://github.com/canada-ca/Open_First_Whitepaper/issues/117

**Comment by gcharest** [comment]
Hi @CalvinRodo !
I will close the issue in the whitepaper and we'll continue the work here.
Thanks!

**Comment by gcharest** [comment]
@ptd-tbs @tallardyce and others. Do you know if we have any guidance on this issue? (I'll be 100% honest, I don't know yet myself but I will keep digging).

**Comment by CalvinRodo** [comment]
From Maggie OReilly in GCMessage Discussion -
[Msg Link ]
(https://message.gccollab.ca/channel/opensourcesoftware?msg=jyXFASiJRn4DN5PZ5) @guillaume.charest The protected info ref: testing etc comes from the Access to Information Act exemptions: Testing procedures, tests and audits

22 The head of a government institution may refuse to disclose any record requested under this Act that contains information relating to testing or auditing procedures or techniques or details of specific tests to be given or audits to be conducted if the disclosure would prejudice the use or results of particular tests or audits.

**Comment by tallardyce** [comment]
Not off the top of my head, sorry!

**Comment by gcharest** [comment]
@CalvinRodo I've been talking to my Cyber colleagues and we're on it. This document will not necessarily state what is or what is not protected in full length but actual guidance will be issued.

Now, for the purpose of this question, I quickly added elements addressing the question without necessarily answering it fully.

**Comment by gcharest** [comment]
Just keeping material for discusion:
Some security considerations to keep in mind when developing software:

* Tests: Unit testing, regression testing, integration testing, stress testing, etc.
* Testing procedures: Manual inspections, Thread modeling, Pen testing, Name of devices, IP addresses, MAC addresses, etc.
* Audits: Results of tests, logs, etc.

*Clarification required about elements of testing mentioned above as protected information.*

* Keeping sensitive data such as credentials secure and separate from source code
* Not storing keys and other sensitive material in systems not approved for that purpose
* Doing code reviews to increase the likelihood of catching bugs, security vulnerabilities, and reduces the risk of committing sensitive data
* For the opening of existing source codes, additional actions will be needed, such as defining the scope, reviewing quality and security, and ensuring compliance specifically on intellectual property.

**Comment by CalvinRodo** [comment]
I've added an issue with my security controls i've documented, might be useful for the guide and relevant to the info you just posted #12

**Comment by gcharest** [comment]
Thanks a lot! Will review shortly and most likely incorporate directly in
the playbook.

Le mar. 10 juill. 2018 20 h 33, Calvin Rodo <notifications@github.com> a
écrit :
