### ISSUE TITLE
Executive version of the Open First Whitepaper

### ISSUE THREAD

**Issue by gcharest** [canada-ca/open-source-logiciel-libre#20]
Whitepaper is lengthy so we need a more succinct version for executives.

Clear guidance for devs, managers, etc.

**Comment by smellems** [comment]
Guidance in Digital Playbook

**Comment by ShadeWyrm** [comment]
Closing unless specific areas of concern can be raised; I don't see a lot of value in producing a summary of the white paper unless explicitly asked to do so.
