### ISSUE TITLE
Add R and Python to the Open Resource Exchange

### ISSUE THREAD

**Issue by manolo20** [canada-ca/open-source-logiciel-libre#22]
https://canada-ca.github.io/ore-ero/open-source-software.html

**Comment by obrien-j** [comment]
Just to mention, centralized assessments of tools / frameworks that have already been approved would allow for deduplication of security assessment teams, ideally leading to more rapid approvals.

**Comment by gcharest** [comment]
This is critical and needs to happen ASAP.

**Comment by dbuijs** [comment]
With respect to R and Python, these are Turing-complete languages, not applications. The actual practical issues with deploying and supporting these languages have to do with how they are implemented. 

For R, perhaps what you're actually hoping for is RStudio on the desktop (or perhaps server hosted)? 

For Python, perhaps what you're hoping for is something like JupyterHub that allows Python code to be run in a notebook?

**Comment by pabrams** [comment]
The link at the top of this page is 404.

**Comment by gcharest** [comment]
@dbuijs Good point regarding programming languages vs applications per say.

I think the idea here will be to ensure that security assessments can be shared. Will be including this part in the directive on [Open Source Software](https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/directives/open-source-software.md)

**Comment by keithdouglas** [comment]
As a application/software security guy it makes little sense to me to do assessments for a lot of development tools, though of course some supply chain stuff makes sense. Better to do supply chain on libraries etc. to use *and* on your colleagues to see that people writing software "know what they are doing" - Python and R seem to "encourage" shadow IT.

**Comment by wardi** [comment]
@keithdouglas Developers and data scientists want to code in Python and R because it makes them more productive. Whether that's "shadow IT" or not depends on management not the tools.

**Comment by gcharest** [comment]
I think we also need to make sure the Open Resources Exchange purpose is properly understood.

It's not a list of TBS sectioned tools and projects, it's a list of used software by departments.

The objective is to share who's using what so that we can more easily share how and why amongst each other.

**Comment by smellems** [comment]
@manolo20 IF you want to create a pull request to add them, I'd be glad to accept it.  PHP is already on the list.

@dbuijs I think the ORE can contain both programming languages for those using them directly and RStudio, Jupyter, Anaconda, .. as well

**Comment by joshuagay** [comment]
Regarding the comment: "With respect to R and Python, these are Turing-complete languages, not applications" 

I think it is important to recognize that both the R Project and Python Software Foundation use the respective terms to refer to a suite of things, one of which is a language specification, but kn both cases you get libraries, language specs, and one or more end-usee applications. 

When a person installs and then executes either R or Python on any major OS, it runs it in "interactive mode" meaning users are running a non-gui application to write in the language and make use of other facilities of the application and in some cases other non-library software that ships with the "language."

Not all programming languages -- even ones where we generally include standard libraries as part of what we mean when we say "language" -- include non-gui terminal applications that allow "interactive" modes like this.

**Comment by ShadeWyrm** [comment]
Closing both languages are pending review :
https://github.com/canada-ca/ore-ero/pull/805
+
https://github.com/canada-ca/ore-ero/pull/804
