### ISSUE TITLE
Importance of policy from TBS

### ISSUE THREAD

**Issue by gcharest** [canada-ca/open-source-logiciel-libre#25]
Karen from Agriculture:

Departments are on their own to write their internal policies since there's not currently an overarching policy.

Diversity of OSS will need to be reflected in the policies that will enable them.

**Comment by KingBain** [comment]
An overarching policy is key for big-idea initiatives  like this. A TBS pin works but there are still methods for departments to circumnavigate around them.

I'd actually talk to @ptd-tbs about lessons learned from the PANDU policy work and amendment.

**Comment by gcharest** [comment]
Very good point. Will definitely take it in consideration!

Le dim. 30 sept. 2018 20 h 06, John Bain <notifications@github.com> a
écrit :

**Comment by uferrpi** [comment]
I suggest the TBS policy should apply to all departments. It should also be closely link to mandatory market analysis and procurement directives.

**Comment by gcharest** [comment]
So, from a policy perspective, I think we can say that the main points are now covered in the directive on management of IT. Still need guidance as to how though.
