### ISSUE TITLE
Users who wish not to disclose their emails

### ISSUE THREAD

**Issue by mgifford** [canada-ca/open-source-logiciel-libre#37]
With:

> Employees must use their full name and Government of Canada email address for all code contributions to public repositories while acting within the scope of their duties or employment.

What do we do if GC employees are facing harassment online? There are people out there who have good reasons to not want to publicly share their full name and email address.  Can they not contribute under an alias as they might well be doing already?  Not sure why this is in here.

**Comment by gcharest** [comment]
Hmm, I think I saw a way for obfuscating the email address (re: not sharing the email address)

Regarding the IP, we might need a better way of associating contributions and IP...

Anybody?

**Comment by mgifford** [comment]
Drupal does allow you to identify if the contribution should be attributed to the developer, the vendor or the client that is paying for the work. I don't know any other open source community that allows for this.  

It might be useful to simply put in "...  where the community allows" phrase.

**Comment by gcharest** [comment]
We might need a more universal approach :thinking:

**Comment by ShadeWyrm** [comment]
Closing this. The word 'must' no longer exists for these sections, and the text :

"However, Government of Canada employees have Moral Rights and as the author of a work has the right to the integrity of the work and the right to be associated with the work as its author by name or under a pseudonym and the right to remain anonymous."

Should provide a basis for employees to opt out of their email being presented.

**Comment by smellems** [comment]
This is still there, even if it's "should" now:

> Employees should use their full name and Government of Canada email address for all code contributions to public repositories while acting within the scope of their duties or employment.

This is about using your GC email in commits instead of a personal email.  It was a way to try and identify all commits by GC.  I guess the moral right to be anonymous might contradicts that.  But commits always have an email associated, although it might not need to be a real email..

**Comment by ShadeWyrm** [comment]
I think this is an area we can't "win" in and find language that would make everyone happy - I'd rather leave it a bit ambiguous and enable both parties while strongly encouraging individuals to use their GoC email address. Anyone needing further guidance can always reach out to TBS. ;)

If anyone can come up with creative us of language that clarifies the point further, I'd be happy to push the change in.

**Comment by smellems** [comment]
I'm ok with that.  I just wanted to add more information on the issue
