### ISSUE TITLE
IP still belongs to the Crown?

### ISSUE THREAD

**Issue by mgifford** [canada-ca/open-source-logiciel-libre#38]
So I'm not sure how 

> IP still belongs to the Crown 

applies.  Say if there's a bug in Drupal.  That's already GPL.  If you're contributing to that project it will be under the GPL license.  There is no way that the Drupal community is going to track a patch that that is dual licensed or licensed under anything other than a GPL compatible license. 

Can we remove this from https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/guides/contributing-to-open-source-software.md

**Comment by gcharest** [comment]
That is fair but unless there is a CLA signed with the specific clause that contributions IP must be transferred to the project "owners", the IP of a contribution remains with the person that has contributed, or that person's employer if there's such an agreement in place.

As such, each contribution belongs to many individuals, it just so happen that all those contributions were made under the same licence granting all others with the same rights.

**Comment by mgifford** [comment]
In theory this is the case. However in practice each project has a chosen license which all contributions fall under.  I think you'd be hard pressed to find a contribution to an open source project that allowed the project owner to select a different license for their contribution than the one that came with the project.  

Even if the GC released a dual license project, you're not going to want to be tracking contributions by folks who might object to the Crown Copyright.

**Comment by gcharest** [comment]
Oh, totally agree on the choice of licence. The guidance will need to clearly indicate that the contribution needs to be under the project's licence, not a new one.

**Comment by smellems** [comment]
Same as #60 

More recent discussion there
