### ISSUE TITLE
Pointing to many reasons to contribute to open source.

### ISSUE THREAD

**Issue by mgifford** [canada-ca/open-source-logiciel-libre#39]
I'm thinking about:

> To make changes in open source software, engage with the community and submit your changes upstream to ensure that your modifications are supported by future updates.

And wondering if there is a way to put in a link to:
https://technology.blog.gov.uk/category/open-source/

make it clear some of the reasons why we're doing this.  There are some golden blog posts here.  Ensuring modifications are supported is just one.

**Comment by gcharest** [comment]
Maybe we can link to it but in the guidance itself, we may want to put the actual reasons in there?

**Comment by smellems** [comment]
I think why we did'nt include reasons to use/publish/contribute to OSS (or removed them at some point), is that those reasons are in the whitepaper and now the Directive on IT says you have to do it.  We weren't trying to convince you anymore.  Tho contributing is'nt in the directive directly..

**Comment by gcharest** [comment]
@smellems

True, I think that the problem of the white paper is that people's attention span download s too short to read through it 😋

Also, v0.1 still hasn't been published... I keep bringing it up but sausage making will be sausage making.

**Comment by mgifford** [comment]
It's worth noting that just because just because TBS puts out a policy, doesn't mean that people actually change their behavior.  It's rather sad what I've seen with accessibility in government sites. There's the assumption that if it's been made public, someone verified that it is accessible.  This often just isn't the case.  There are other policies like the Green Procurement Policy that have been intact since 2006 but that I am not sure ever really factor into procurement decisions.  

People need to know the why. 

Maybe we need a series of posters to help change the patters and that fit our goldfish sized attention spans.  Perhaps we could just riff on the UK's model:
  https://twitter.com/gdsteam/status/843850951962300416

Not sure if this is the best article for this, but it's got some good points:
https://technology.blog.gov.uk/2018/11/05/11-barriers-to-coding-in-the-open-and-how-to-overcome-them/

People have to understand that working in the open can help others, but more importantly it can help your project become more robust and help you become a better developer too.

**Comment by gcharest** [comment]
That might need to be tied to a broader communication strategy though. Should it sit in the guidelines? I'd love to add our experience (departments) as a series of blog posts.

**Comment by ShadeWyrm** [comment]
The playbook has been updated with the link in the initial post :

https://wiki.gccollab.ca/GoC_Open_Source_Playbook#External_Sources

The 11 Barriers was fun to read, and I'll be looking to break them down! If you notice any not being explicitly dealt with please let me know. :)

**Comment by ShadeWyrm** [comment]
Oh - I just realized I didn't mention - we have to be very very careful with external linking for this material - hence why the Playbook was created.
