### ISSUE TITLE
Nix Gcdevexchange reference

### ISSUE THREAD

**Issue by mgifford** [canada-ca/open-source-logiciel-libre#40]
Would be good to remove https://gcdevexchange-carrefourproggc.org/ until it is actually an option.

I do wonder if it is worth mentioning that managers may have the ability to buy support for open source tools for under $10k on their credit card.  There is lots of work that could be fairly informally done this way.

**Comment by gcharest** [comment]
Yes, we need to remove it, unfortunately!

**Comment by mgifford** [comment]
Where is the grumpy face icon when you need it?

**Comment by gcharest** [comment]
:grimace:

**Comment by gcharest** [comment]
Nope

**Comment by gcharest** [comment]
:grimacing: => grimacing

**Comment by smellems** [comment]
I removed the last note about the GCDevExchange.
