### ISSUE TITLE
General comment on guidelines

### ISSUE THREAD

**Issue by JJcodium** [canada-ca/open-source-logiciel-libre#44]
In general, I recommend to

1. Separate the guidelines as such : Guideline on the Use of Open Source Software, Guideline on Modifications and Source Code Contribution to Open Source Software Projects, and Guideline on Leading Open Source Software Projects. I would not put any infos about customizing OSS.

2.	The Table of Contents should be something like
a.	Purpose
b.	Introduction
c.	Guideline 1 Title
d.	Guideline 2 Title
e.	Key Terms and Definitions
f.	Annex A: Title A
g.	Annex B: Title B
h.	References

3.	In the Introduction, you should refer to the other guidelines

**Comment by gcharest** [comment]
Thanks!

**Comment by ShadeWyrm** [comment]
The format has been changed to provide a layout that should match final web content.

Closing. :)
