### ISSUE TITLE
Ensuring that open source software be actively....

### ISSUE THREAD

**Issue by mgifford** [canada-ca/open-source-logiciel-libre#56]
Just looking at the last line here:

https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/requirements/using-open-source-software.md

> Requirements
> 
> Ensuring that open source software be actively and fairly considered for all new technologies, upgrades or migrations, including cloud solutions.

Any reason not to just remove it? 

It's already in a "Requirements for using open source software" section.  I'm not sure what it ads. 

What would someone look for?  When wouldn't open source be appropriate?

**Comment by gcharest** [comment]
Good point, I think we may need to simply remove the requirements since they are covered in the Directive already?

**Comment by mgifford** [comment]
That would be fine I think.

**Comment by gcharest** [comment]
@smellems Are you OK with removing the `Requirements` files as well?

**Comment by smellems** [comment]
I created a branch [with-requirements](https://github.com/canada-ca/open-source-logiciel-libre/tree/with-requirements) and removed the Requirements from master.
