### ISSUE TITLE
Are we being too specific?

### ISSUE THREAD

**Issue by mgifford** [canada-ca/open-source-logiciel-libre#57]
I'm just looking at https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/guides/contributing-to-open-source-software.md#verify-open-source-software-licence

> Verify Open Source Software Licence
> 
> GC can contribute to all software licensed under an Open Source Initiative approved license or a Free Software Foundation free software licence.

Does this mean that the GC cannot contribute to projects that are listed under the Public Domain? 

I'm just wondering what licenses are potentially a problem. Lots of government work has contributed to proprietary projects owned by a variety of vendors. 

There are good reasons to select software that is leveraging an approved open source license.  There are reasons to select one of the preferred licenses when releasing a project. But if a government department is already using a piece of software and they want to contribute to it, why is the license a consideration? It seems the norm is to do this for proprietary tools at the moment. 

Also, is it "Licence" or "License" in Canada?  My spellcheck thinks it is the latter.

**Comment by gcharest** [comment]
This is a legitimate question but I think we're more trying to capture the 99% scenario here (a bit more than the 80% :wink: ).

There's a review process done by the OSI and the FSF to determine if those licences are deemed open source.

By not including a list, we would revert to each department doing the legal work of reviewing licences. That would lead to duplication of efforts and : 

> Too much work, not going to do it. Y'all can't contribute.

There's already a thorough legal review based on the key rights and conditions we have identified as Open source in the Whitepaper by these two bodies. It's also industry supported so I think this approach gives us a lot of flexibility to get started.

We need to get the ball rolling, get people familiar with the processes. As it becomes standard operating procedure, people will better understand and will be able to assess if they also need to explore non OSI/FSF approved licences.

Overall, I think we could simply add a note with this kind of angle:
If a licence is not covered by any of these organizations, further legal counsel can be seeked to clarify if contributions are recommended.

What do you think? @mgifford @smellems

**Comment by mgifford** [comment]
That works for me.  Makes it less, "you have to use one of these" to "if you use anything else, you're going to have to get it cleared yourself".  I think that's a better message.

**Comment by gcharest** [comment]
Makes sense, will adapt accordingly!

Le mer. 1 mai 2019 20 h 16, Mike Gifford <notifications@github.com> a
écrit :

**Comment by smellems** [comment]
I added the sentence to clarify that you could contribute to open projects using other licences, if you do a legal review to see if contributions are recomended
