### ISSUE TITLE
IP still belongs to the Crown

### ISSUE THREAD

**Issue by mgifford** [canada-ca/open-source-logiciel-libre#60]
Looking here https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/guides/contributing-to-open-source-software.md#other-notes

So how would someone submit a patch, module, documentation or a theme to Drupal.org if in the end "IP still belongs to the Crown".  There is nothing which allows you to specify this in Drupal.org 

https://www.drupal.org/about/licensing
https://www.drupal.org/docs/user_guide/en/copyright.html

If you want to submit a whole new project on GitHub, knock your socks off. However, existing projects have licenses already which usually aren't the Crown (or at least not ours).

**Comment by gcharest** [comment]
Agreed but unless there's a CLA in place in the project to transfer the IP,
it remains with the author, which would be a government employee in this
case.

Contributions are just made under the same licences.

Le mar. 30 avr. 2019 10 h 52, Mike Gifford <notifications@github.com> a
écrit :

**Comment by LaurentGoderre** [comment]
I find that part problematic too!  What is the rationale to retain IP for patches and bug fixes? I understand for GC projects but not for external contribution.

**Comment by gcharest** [comment]
The rationale is simply based on how the law works.

Le mar. 30 avr. 2019 11 h 19, Laurent Goderre <notifications@github.com> a
écrit :

**Comment by mgifford** [comment]
So is this something that has to be brought up with Justice?  Just seems like a silly thing based on old ideas.

**Comment by smellems** [comment]
Those notes should be removed of incorporated in the text.  IP is a general term that also applies to Trademarks and Patents.  This is about Copyrights.

@mgifford This is form the Drupal Licensing page

5. Who holds the copyright for Drupal?
> Drupal and contributed modules and themes include code written by thousands of different people. All Drupal contributors retain copyright on their code, but agree to release it under the same license as Drupal.

My understanding is the same as @gcharest.  If the Crown contributes to Drupal it get to keep the copyright for that contribution. Unless there's a CLA that explicitly ask for it.

**Comment by gcharest** [comment]
It's a matter of having approvals from the IP owner to grant the rights. There could be different ways of dealing with this but if you work for Bank A, the IP you generate while coding isn't yours, it's the companies. Same thing here, it's not mine, it's the Government's.

So, by default, IP remains with the Crown unless we have the process lined up for authorizing transfer of IP.

When contributing to project X as an individual, IP/Copyright still remains with the individual contributors but they're granting the same rights and conditions as the project to the rest of the world because their contributions are under the same licence.

That's why CLAs have been introduced, to have a contract in which projects were to take contributions as well as the associated IP.

**Comment by mgifford** [comment]
Are there example CLAs (Client Level Agreements??) which are being used?  So many contracts will need to change to make this easy.

**Comment by gcharest** [comment]
Not in the GC and we recommend against creating those. Most communities
have moved to DCO instead because CLAs were creating barriers for people
and companies to contribute.

Le jeu. 2 mai 2019 08 h 50, Mike Gifford <notifications@github.com> a
écrit :

**Comment by smellems** [comment]
Contributor License Agreement (CLA)

Developer Certificate of Origin (DCO)

**Comment by gcharest** [comment]
:grin: thanks for writing out long!

Le jeu. 2 mai 2019 08 h 56, Sébastien Lemay <notifications@github.com> a
écrit :

**Comment by gcharest** [comment]
I know not everyone has the tone to read a book but this one was an eye opener from the legal dimension of open source software:

https://www.goodreads.com/book/show/34977796-open-source-for-business

**Comment by mgifford** [comment]
I haven't read that book yet. Thanks.

**Comment by keithdouglas** [comment]
There's also _Open source licensing : software freedom and intellectual property law_.

**Comment by ShadeWyrm** [comment]
As changes to the document have occurred this no longer seems to be referenced. Please create a new issue if further discussion is required. :)
