### ISSUE TITLE
Change "Prior to Starting" to "Open Source Software Acquisition"

### ISSUE THREAD

**Issue by KingBain** [canada-ca/open-source-logiciel-libre#94]
I noticed the "Prior to Starting" section isnt following the other naming convention used for the other sections. is that on purpose ?

IMO I think the section should be renamed to "Open Source Software Acquisition" to better fit in with the other sections.

If attention needs to be driven there as a first stop, maybe the standard could be modified to actually say that ? 🤷‍♂

**Comment by ShadeWyrm** [comment]
Fixed.
